# -*- coding: utf-8 -*-
"""Generate supplementary lesson files into ../topics using the same JSON
schema as the grammar files.

Each topic is authored as a compact list of "blocks". Blocks are expanded into
the flat `lessons` array exactly like the grammar files:

  ("h1", text)  -> major section heading   (htmlTag 1, language fa)
  ("h2", text)  -> subsection heading       (htmlTag 2, language fa)
  ("fa", text)  -> Persian body text        (htmlTag 0, language fa)
  ("en", text)  -> English example          (htmlTag 0, language en)

`title` is set to the nearest preceding heading (h1/h2), matching the grammar
files. `order` starts at 1 and increments. `voiceId` is 0 everywhere.
"""

import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "topics")


def build(topic):
    lessons = []
    order = 1
    current_title = topic["name"]
    for kind, text in topic["blocks"]:
        if kind == "h1":
            html_tag, lang = 1, "fa"
            current_title = text
            content = text
        elif kind == "h2":
            html_tag, lang = 2, "fa"
            current_title = text
            content = text
        elif kind == "en":
            html_tag, lang = 0, "en"
            content = text
        else:  # fa
            html_tag, lang = 0, "fa"
            content = text
        lessons.append({
            "title": current_title,
            "htmlTag": html_tag,
            "content": content,
            "order": order,
            "language": lang,
            "voiceId": 0,
        })
        order += 1
    return {
        "grammar": {
            "name": topic["name"],
            "levelId": topic["levelId"],
            "order": topic["order"],
            "estimatedTimeMinutes": topic.get("mins", 8),
            "description": topic["description"],
            "parentGrammarId": 0,
            "lessons": lessons,
        }
    }


TOPICS = [
    # ============================= A1 grammar gaps =============================
    {
        "file": "a1-question-words.json",
        "name": "Question words (wh-)",
        "levelId": 1, "order": 1, "mins": 8,
        "description": "کلمات پرسشی برای ساختن سوال‌های اطلاعاتی.",
        "blocks": [
            ("h1", "کلمات پرسشی چه هستند؟"),
            ("fa", "کلمات پرسشی مثل what، where، who، when، why و how برای سوال‌هایی به کار می‌روند که جواب آن‌ها فقط بله یا خیر نیست، بلکه یک اطلاعات تازه است. این کلمات معمولا در ابتدای سوال می‌آیند."),
            ("h2", "کاربرد 1: پرسیدن درباره چیز یا شخص"),
            ("en", "What is your name?"),
            ("fa", "کلمه what درباره یک چیز یا اطلاعات می‌پرسد. who هم به همین شکل اما درباره شخص استفاده می‌شود."),
            ("en", "Who is that man?"),
            ("fa", "اینجا who درباره یک شخص سوال می‌کند. جواب آن نام یا نقش یک نفر است."),
            ("h2", "کاربرد 2: پرسیدن درباره مکان و زمان"),
            ("en", "Where do you live?"),
            ("fa", "where درباره مکان می‌پرسد و when درباره زمان. هر دو در ابتدای جمله می‌آیند."),
            ("en", "When does the class start?"),
            ("fa", "در این سوال when زمان شروع کلاس را می‌پرسد. ساختار سوال با does ساخته شده است."),
            ("h2", "نکته مهم"),
            ("fa", "بعد از کلمه پرسشی معمولا یک فعل کمکی مثل is، do یا does می‌آید و سپس فاعل. ترتیب درست باعث می‌شود سوال طبیعی به نظر برسد."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Why are you late?"),
            ("fa", "why درباره دلیل می‌پرسد. جواب آن معمولا با because شروع می‌شود."),
            ("en", "How do you go to work?"),
            ("fa", "how درباره روش یا حالت می‌پرسد. اینجا درباره وسیله رفتن به محل کار سوال شده است."),
        ],
    },
    {
        "file": "a1-imperatives.json",
        "name": "Imperatives",
        "levelId": 1, "order": 2, "mins": 6,
        "description": "جمله‌های امری برای دستور، راهنمایی و دعوت.",
        "blocks": [
            ("h1", "جمله امری چیست؟"),
            ("fa", "جمله امری برای دادن دستور، راهنمایی، خواهش یا دعوت به کار می‌رود. در این جمله‌ها فاعل (you) گفته نمی‌شود و جمله مستقیم با شکل پایه فعل شروع می‌شود."),
            ("h2", "کاربرد 1: دستور و راهنمایی مثبت"),
            ("en", "Open the window, please."),
            ("fa", "جمله با فعل open و بدون فاعل شروع شده است. کلمه please آن را مودبانه‌تر می‌کند."),
            ("en", "Turn left at the corner."),
            ("fa", "این جمله یک راهنمایی مسیر است. شکل پایه فعل turn در ابتدا آمده است."),
            ("h2", "کاربرد 2: امر منفی با don't"),
            ("en", "Don't worry."),
            ("fa", "برای منفی کردن امر از don't پیش از فعل استفاده می‌کنیم. این ساختار یک هشدار یا دلگرمی است."),
            ("en", "Don't be late."),
            ("fa", "اینجا don't با فعل be آمده و معنای «دیر نکن» می‌دهد."),
            ("h2", "نکته مهم"),
            ("fa", "جمله امری همیشه با شکل پایه فعل ساخته می‌شود و به فاعل نیاز ندارد. افزودن please لحن را مودبانه می‌کند و در موقعیت‌های رسمی مهم است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Please sit down."),
            ("fa", "این یک دعوت مودبانه برای نشستن است. please می‌تواند اول یا آخر جمله بیاید."),
            ("en", "Let's go now."),
            ("fa", "با let's یک پیشنهاد گروهی می‌سازیم که خود گوینده هم در آن شرکت دارد."),
        ],
    },
    {
        "file": "a1-prepositions-of-place-and-time.json",
        "name": "Prepositions of place and time",
        "levelId": 1, "order": 3, "mins": 9,
        "description": "حروف اضافه in، on و at برای مکان و زمان.",
        "blocks": [
            ("h1", "حروف اضافه مکان و زمان"),
            ("fa", "سه حرف اضافه پرکاربرد in، on و at هم برای مکان و هم برای زمان استفاده می‌شوند. انتخاب درست آن‌ها به این بستگی دارد که درباره یک نقطه صحبت می‌کنیم یا یک سطح یا یک فضای بزرگ‌تر."),
            ("h2", "کاربرد 1: مکان با in، on، at"),
            ("en", "The keys are on the table."),
            ("fa", "on برای چیزی است که روی یک سطح قرار دارد. in برای داخل یک فضا و at برای یک نقطه مشخص به کار می‌رود."),
            ("en", "She is in the kitchen."),
            ("fa", "in نشان می‌دهد شخص داخل یک فضای بسته است. این کاربرد رایج‌ترین معنای in برای مکان است."),
            ("h2", "کاربرد 2: زمان با in، on، at"),
            ("en", "The meeting is at three o'clock."),
            ("fa", "at برای ساعت دقیق استفاده می‌شود. on برای روزها و in برای ماه‌ها و سال‌ها به کار می‌رود."),
            ("en", "My birthday is in June."),
            ("fa", "in با ماه‌ها، فصل‌ها و سال‌ها می‌آید. برای روز مشخص از on استفاده می‌کنیم."),
            ("h2", "نکته مهم"),
            ("fa", "یک راه ساده برای یادسپاری: at برای نقطه (ساعت، آدرس دقیق)، on برای سطح یا روز، و in برای فضای بزرگ یا دوره زمانی طولانی‌تر."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We meet on Monday."),
            ("fa", "on با روزهای هفته می‌آید. به همین دلیل برای Monday درست است."),
            ("en", "He is at the bus stop."),
            ("fa", "at برای یک نقطه مشخص مثل ایستگاه اتوبوس مناسب است."),
        ],
    },
    {
        "file": "a1-adverbs-of-frequency.json",
        "name": "Adverbs of frequency",
        "levelId": 1, "order": 4, "mins": 7,
        "description": "قیدهای تکرار مثل always، usually و never.",
        "blocks": [
            ("h1", "قیدهای تکرار"),
            ("fa", "قیدهای تکرار نشان می‌دهند یک کار هر چند وقت یک‌بار انجام می‌شود. مهم‌ترین آن‌ها always، usually، often، sometimes و never هستند و معمولا با حال ساده به کار می‌روند."),
            ("h2", "کاربرد 1: جای قید با فعل‌های معمولی"),
            ("en", "I always drink tea in the morning."),
            ("fa", "قید تکرار always پیش از فعل اصلی drink آمده است. این جای معمول قید با فعل‌های ساده است."),
            ("en", "She often works late."),
            ("fa", "often هم پیش از فعل works قرار گرفته و نشان می‌دهد این کار زیاد تکرار می‌شود."),
            ("h2", "کاربرد 2: جای قید با فعل be"),
            ("en", "He is never late."),
            ("fa", "با فعل be قید تکرار بعد از فعل می‌آید، نه پیش از آن. به همین دلیل never بعد از is آمده است."),
            ("en", "They are usually busy on Fridays."),
            ("fa", "اینجا هم usually بعد از فعل are قرار گرفته است، چون فعل be قانون جداگانه دارد."),
            ("h2", "نکته مهم"),
            ("fa", "قید تکرار پیش از فعل اصلی اما بعد از فعل be می‌آید. کلمه never خودش معنای منفی دارد، پس جمله را دوباره منفی نمی‌کنیم."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We sometimes eat out."),
            ("fa", "sometimes تکرار کم را نشان می‌دهد و پیش از فعل eat آمده است."),
            ("en", "I usually wake up early."),
            ("fa", "usually یک عادت معمول را بیان می‌کند و در جای درست پیش از فعل قرار دارد."),
        ],
    },
    {
        "file": "a1-possessive-s.json",
        "name": "Possessive 's",
        "levelId": 1, "order": 5, "mins": 7,
        "description": "نشان دادن مالکیت با افزودن s و آپاستروف.",
        "blocks": [
            ("h1", "نشان دادن مالکیت با 's"),
            ("fa", "در انگلیسی برای گفتن اینکه چیزی به چه کسی تعلق دارد، معمولا به نام شخص یک آپاستروف و s اضافه می‌کنیم. این ساختار جای عبارت‌های طولانی‌تر را می‌گیرد."),
            ("h2", "کاربرد 1: مالکیت برای یک نفر"),
            ("en", "This is Sara's book."),
            ("fa", "با افزودن 's به Sara نشان داده‌ایم که کتاب به سارا تعلق دارد. این کوتاه‌تر از گفتن the book of Sara است."),
            ("en", "My brother's car is new."),
            ("fa", "اینجا 's روی brother آمده و مالکیت ماشین را مشخص می‌کند."),
            ("h2", "کاربرد 2: مالکیت برای جمع"),
            ("en", "The students' room is upstairs."),
            ("fa", "وقتی اسم جمع به s ختم می‌شود، فقط یک آپاستروف بعد از s می‌گذاریم و دیگر s اضافه نمی‌کنیم."),
            ("en", "The children's toys are here."),
            ("fa", "children جمع بی‌قاعده است و به s ختم نمی‌شود، پس مثل حالت مفرد 's می‌گیرد."),
            ("h2", "نکته مهم"),
            ("fa", "برای اشخاص و موجودات زنده معمولا از 's استفاده می‌کنیم، اما برای اشیا بیشتر ساختار of طبیعی‌تر است، مثل the door of the car."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Tom's phone is on the desk."),
            ("fa", "'s روی نام Tom مالکیت تلفن را نشان می‌دهد."),
            ("en", "It is my friend's idea."),
            ("fa", "اینجا 's مشخص می‌کند که ایده متعلق به دوست گوینده است."),
        ],
    },
    {
        "file": "a1-have-got.json",
        "name": "Have got",
        "levelId": 1, "order": 6, "mins": 7,
        "description": "بیان مالکیت و داشتن با have got.",
        "blocks": [
            ("h1", "ساختار have got"),
            ("fa", "have got یک راه رایج به‌ویژه در انگلیسی بریتانیایی برای گفتن «داشتن» است. معنای آن با have تنها تفاوتی ندارد، اما ساختار سوال و منفی آن متفاوت است."),
            ("h2", "کاربرد 1: جمله مثبت"),
            ("en", "I have got two sisters."),
            ("fa", "have got داشتن دو خواهر را بیان می‌کند. در حالت گفتاری معمولا به I've got کوتاه می‌شود."),
            ("en", "She has got a new job."),
            ("fa", "با he، she و it از has got استفاده می‌کنیم. اینجا has got داشتن شغل تازه را نشان می‌دهد."),
            ("h2", "کاربرد 2: سوال و منفی"),
            ("en", "Have you got a pen?"),
            ("fa", "برای سوال، have یا has را به ابتدای جمله می‌بریم. به do یا does نیاز نداریم."),
            ("en", "He hasn't got a car."),
            ("fa", "برای منفی، not را به have یا has اضافه می‌کنیم. اینجا hasn't got یعنی ماشین ندارد."),
            ("h2", "نکته مهم"),
            ("fa", "have got بیشتر در زمان حال و برای مالکیت به کار می‌رود. برای گذشته از had استفاده می‌کنیم، نه had got در این معنا."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "They have got a big house."),
            ("fa", "have got داشتن یک خانه بزرگ را نشان می‌دهد و با فاعل جمع they آمده است."),
            ("en", "Has she got your number?"),
            ("fa", "این سوال با has شروع شده چون فاعل she است."),
        ],
    },

    # ============================= A2 grammar gaps =============================
    {
        "file": "a2-possessive-pronouns.json",
        "name": "Possessive pronouns",
        "levelId": 2, "order": 1, "mins": 7,
        "description": "ضمایر ملکی مثل mine، yours و his.",
        "blocks": [
            ("h1", "ضمیر ملکی چیست؟"),
            ("fa", "ضمیر ملکی مثل mine، yours، his، hers و ours جای یک اسم و صفت ملکی را با هم می‌گیرد. به کمک آن از تکرار اسم جلوگیری می‌کنیم."),
            ("h2", "کاربرد 1: جای‌گزین اسم"),
            ("en", "This book is mine."),
            ("fa", "به‌جای گفتن this is my book، از mine استفاده کرده‌ایم. ضمیر ملکی به‌تنهایی و بدون اسم می‌آید."),
            ("en", "That seat is yours."),
            ("fa", "yours جای your seat را گرفته است و مالکیت را بدون تکرار اسم نشان می‌دهد."),
            ("h2", "کاربرد 2: مقایسه مالکیت"),
            ("en", "My car is old, but hers is new."),
            ("fa", "hers جای her car را گرفته است تا اسم car دوباره تکرار نشود."),
            ("en", "Our house is bigger than theirs."),
            ("fa", "theirs به‌جای their house آمده و دو مالکیت را با هم مقایسه کرده است."),
            ("h2", "نکته مهم"),
            ("fa", "تفاوت مهم این است که صفت ملکی (my، your) پیش از اسم می‌آید، اما ضمیر ملکی (mine، yours) جای اسم را می‌گیرد و تنها به کار می‌رود."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "These keys are his."),
            ("fa", "his هم می‌تواند صفت و هم ضمیر ملکی باشد؛ اینجا به‌تنهایی آمده و ضمیر است."),
            ("en", "The choice is ours."),
            ("fa", "ours جای our choice را گرفته و مالکیت را به‌روشنی نشان می‌دهد."),
        ],
    },
    {
        "file": "a2-reflexive-pronouns.json",
        "name": "Reflexive pronouns",
        "levelId": 2, "order": 2, "mins": 7,
        "description": "ضمایر انعکاسی مثل myself و yourself.",
        "blocks": [
            ("h1", "ضمیر انعکاسی چیست؟"),
            ("fa", "ضمیر انعکاسی مثل myself، yourself و himself وقتی به کار می‌رود که فاعل و مفعول جمله یک نفر باشند. این ضمیر نشان می‌دهد کار به خود فاعل برمی‌گردد."),
            ("h2", "کاربرد 1: کار به خود فاعل برمی‌گردد"),
            ("en", "I hurt myself."),
            ("fa", "چون فاعل و مفعول هر دو «من» هستند، از myself استفاده شده است. کار آسیب به خود گوینده برگشته است."),
            ("en", "She taught herself English."),
            ("fa", "herself نشان می‌دهد که او بدون کمک دیگران و به‌تنهایی یاد گرفته است."),
            ("h2", "کاربرد 2: تاکید"),
            ("en", "I made this cake myself."),
            ("fa", "اینجا myself برای تاکید آمده و یعنی خودم و بدون کمک کسی این کار را کردم."),
            ("en", "The manager himself called me."),
            ("fa", "himself روی اهمیت موضوع تاکید می‌کند: شخصا خود مدیر تماس گرفت."),
            ("h2", "نکته مهم"),
            ("fa", "عبارت by myself یعنی «تنها» یا «بدون کمک». همه فعل‌ها ضمیر انعکاسی نمی‌گیرند؛ مثلا معمولا نمی‌گوییم I feel myself good."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "They enjoyed themselves at the party."),
            ("fa", "فعل enjoy معمولا با ضمیر انعکاسی می‌آید و یعنی به آن‌ها خوش گذشت."),
            ("en", "He lives by himself."),
            ("fa", "by himself یعنی او تنها زندگی می‌کند."),
        ],
    },
    {
        "file": "a2-used-to.json",
        "name": "Used to",
        "levelId": 2, "order": 3, "mins": 8,
        "description": "بیان عادت‌ها و حقایق گذشته با used to.",
        "blocks": [
            ("h1", "ساختار used to"),
            ("fa", "used to برای کارها یا حالت‌هایی به کار می‌رود که در گذشته عادت یا حقیقت بودند اما حالا دیگر ادامه ندارند. این ساختار تفاوت گذشته و حال را برجسته می‌کند."),
            ("h2", "کاربرد 1: عادت گذشته"),
            ("en", "I used to play football every weekend."),
            ("fa", "used to نشان می‌دهد که این کار در گذشته عادت بوده اما اکنون دیگر انجام نمی‌شود."),
            ("en", "She used to live in Tehran."),
            ("fa", "این جمله یک حالت گذشته را بیان می‌کند که حالا تغییر کرده است."),
            ("h2", "کاربرد 2: سوال و منفی"),
            ("en", "Did you use to smoke?"),
            ("fa", "در سوال و منفی فعل به شکل use to برمی‌گردد و از did کمک می‌گیریم، پس d از use to حذف می‌شود."),
            ("en", "He didn't use to like coffee."),
            ("fa", "اینجا didn't use to یعنی در گذشته قهوه دوست نداشت، اما شاید حالا دوست دارد."),
            ("h2", "نکته مهم"),
            ("fa", "used to فقط برای گذشته است و شکل حال ندارد. برای عادت‌های فعلی از حال ساده و قید تکرار استفاده می‌کنیم."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We used to walk to school."),
            ("fa", "این جمله یک عادت گذشته دوران مدرسه را بیان می‌کند."),
            ("en", "There used to be a cinema here."),
            ("fa", "used to be یک حقیقت گذشته را نشان می‌دهد که دیگر درست نیست."),
        ],
    },
    {
        "file": "a2-tag-questions.json",
        "name": "Tag questions",
        "levelId": 2, "order": 4, "mins": 8,
        "description": "سوال‌های ضمیمه برای تایید گرفتن در پایان جمله.",
        "blocks": [
            ("h1", "سوال ضمیمه چیست؟"),
            ("fa", "سوال ضمیمه یک پرسش کوتاه در پایان جمله است که برای تایید گرفتن یا اطمینان بیشتر به کار می‌رود. شکل آن به فعل و مثبت یا منفی بودن جمله اصلی بستگی دارد."),
            ("h2", "کاربرد 1: جمله مثبت، ضمیمه منفی"),
            ("en", "You are a student, aren't you?"),
            ("fa", "چون جمله اصلی مثبت است، سوال ضمیمه منفی می‌شود. از همان فعل کمکی جمله استفاده می‌کنیم."),
            ("en", "She likes tea, doesn't she?"),
            ("fa", "جمله با حال ساده ساخته شده، پس در ضمیمه از doesn't کمک می‌گیریم."),
            ("h2", "کاربرد 2: جمله منفی، ضمیمه مثبت"),
            ("en", "He isn't here, is he?"),
            ("fa", "چون جمله اصلی منفی است، سوال ضمیمه مثبت می‌شود. این تعادل قانون اصلی سوال‌های ضمیمه است."),
            ("en", "They didn't call, did they?"),
            ("fa", "جمله منفی با گذشته ساده است، پس ضمیمه مثبت با did ساخته شده است."),
            ("h2", "نکته مهم"),
            ("fa", "اگر جمله مثبت باشد ضمیمه منفی است و برعکس. ضمیر ضمیمه باید با فاعل جمله اصلی هماهنگ باشد."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "It's cold today, isn't it?"),
            ("fa", "جمله مثبت با is آمده، پس ضمیمه isn't it می‌شود."),
            ("en", "You can swim, can't you?"),
            ("fa", "فعل کمکی can در جمله است، پس در ضمیمه هم از can't استفاده می‌کنیم."),
        ],
    },
    {
        "file": "a2-so-such-too-enough.json",
        "name": "So, such, too, enough",
        "levelId": 2, "order": 5, "mins": 8,
        "description": "تشدید و اندازه‌گیری با so، such، too و enough.",
        "blocks": [
            ("h1", "تشدید و اندازه"),
            ("fa", "کلمات so، such، too و enough همگی شدت یا اندازه یک ویژگی را بیان می‌کنند، اما در جای متفاوتی از جمله می‌آیند و معنای کمی فرق دارند."),
            ("h2", "کاربرد 1: so و such"),
            ("en", "The film was so boring."),
            ("fa", "so پیش از صفت یا قید می‌آید و آن را تشدید می‌کند. در اینجا روی boring تاکید کرده است."),
            ("en", "It was such a boring film."),
            ("fa", "such پیش از یک گروه اسمی می‌آید (a boring film)، در حالی که so تنها پیش از صفت قرار می‌گیرد."),
            ("h2", "کاربرد 2: too و enough"),
            ("en", "This coffee is too hot."),
            ("fa", "too یعنی بیش از حد لازم و بار منفی دارد. اینجا یعنی قهوه آنقدر داغ است که مناسب نیست."),
            ("en", "He isn't tall enough."),
            ("fa", "enough یعنی به اندازه کافی و بعد از صفت می‌آید. اینجا یعنی قد او کافی نیست."),
            ("h2", "نکته مهم"),
            ("fa", "enough بعد از صفت اما پیش از اسم می‌آید: tall enough ولی enough money. too معنای منفی «زیادی» دارد و با very که فقط تشدید است فرق می‌کند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We have enough time."),
            ("fa", "enough پیش از اسم time آمده و یعنی وقت کافی داریم."),
            ("en", "She is so kind."),
            ("fa", "so صفت kind را تشدید کرده است."),
        ],
    },

    # ============================= B1 grammar gaps =============================
    {
        "file": "b1-phrasal-verbs.json",
        "name": "Phrasal verbs",
        "levelId": 3, "order": 1, "mins": 9,
        "description": "افعال دوکلمه‌ای و معنای آن‌ها در انگلیسی روزمره.",
        "blocks": [
            ("h1", "فعل عبارتی چیست؟"),
            ("fa", "فعل عبارتی از یک فعل و یک کلمه کوتاه (مثل up، on، off) ساخته می‌شود و معنای آن اغلب با معنای تک‌تک کلمه‌ها فرق دارد. این افعال در انگلیسی روزمره بسیار رایج هستند."),
            ("h2", "کاربرد 1: معنای تازه و مستقل"),
            ("en", "Please turn off the light."),
            ("fa", "turn off یعنی خاموش کردن. این معنی از ترکیب turn و off ساخته شده و باید آن را به‌صورت یک واحد یاد گرفت."),
            ("en", "I get up at seven."),
            ("fa", "get up یعنی از خواب بیدار شدن یا بلند شدن. معنای آن مستقل از get و up است."),
            ("h2", "کاربرد 2: جداشدنی و جدانشدنی"),
            ("en", "Turn the radio on."),
            ("fa", "بعضی افعال عبارتی جداشدنی هستند، یعنی مفعول می‌تواند میان دو بخش بیاید: turn it on."),
            ("en", "She looks after her brother."),
            ("fa", "look after جدانشدنی است؛ مفعول همیشه بعد از کل عبارت می‌آید و نمی‌گوییم look her after."),
            ("h2", "نکته مهم"),
            ("fa", "اگر مفعول یک ضمیر باشد و فعل جداشدنی باشد، ضمیر باید میان دو بخش بیاید: turn it off، نه turn off it."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We ran out of milk."),
            ("fa", "run out of یعنی تمام شدن چیزی. اینجا یعنی شیر تمام شد."),
            ("en", "He gave up smoking."),
            ("fa", "give up یعنی ترک کردن یا دست کشیدن. بعد از آن معمولا فعل ing-دار می‌آید."),
        ],
    },
    {
        "file": "b1-gerunds-and-infinitives.json",
        "name": "Gerunds and infinitives",
        "levelId": 3, "order": 2, "mins": 9,
        "description": "انتخاب میان شکل ing و to پس از فعل‌ها.",
        "blocks": [
            ("h1", "شکل ing یا to؟"),
            ("fa", "بعد از بعضی فعل‌ها شکل ing-دار (gerund) می‌آید و بعد از بعضی دیگر شکل to + فعل (infinitive). انتخاب درست به فعل اول جمله بستگی دارد و باید این الگوها را یاد گرفت."),
            ("h2", "کاربرد 1: فعل‌هایی که ing می‌گیرند"),
            ("en", "I enjoy reading books."),
            ("fa", "بعد از enjoy همیشه شکل ing-دار می‌آید. فعل‌هایی مثل finish و avoid هم همین الگو را دارند."),
            ("en", "She finished doing her homework."),
            ("fa", "بعد از finish فعل به شکل doing آمده است، نه to do."),
            ("h2", "کاربرد 2: فعل‌هایی که to می‌گیرند"),
            ("en", "We decided to leave early."),
            ("fa", "بعد از decide شکل to + فعل می‌آید. فعل‌هایی مثل want و hope هم همین قانون را دارند."),
            ("en", "He wants to learn Spanish."),
            ("fa", "بعد از want از to learn استفاده شده است، نه learning."),
            ("h2", "نکته مهم"),
            ("fa", "بعضی فعل‌ها مثل like هر دو شکل را می‌پذیرند با تفاوت معنایی جزئی. همچنین بعد از حروف اضافه همیشه شکل ing-دار می‌آید: good at swimming."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "They avoided making noise."),
            ("fa", "بعد از avoid شکل ing-دار می‌آید، پس making درست است."),
            ("en", "I hope to see you soon."),
            ("fa", "بعد از hope از to + فعل استفاده می‌کنیم."),
        ],
    },
    {
        "file": "b1-adverbs-and-comparative-adverbs.json",
        "name": "Adverbs and comparative adverbs",
        "levelId": 3, "order": 3, "mins": 8,
        "description": "ساخت قید از صفت و مقایسه با قیدها.",
        "blocks": [
            ("h1", "قید و مقایسه آن"),
            ("fa", "قید چگونگی انجام یک کار را توصیف می‌کند و معمولا با افزودن ly به صفت ساخته می‌شود. قیدها هم مثل صفت‌ها می‌توانند حالت مقایسه‌ای داشته باشند."),
            ("h2", "کاربرد 1: ساخت قید از صفت"),
            ("en", "She speaks clearly."),
            ("fa", "قید clearly از صفت clear با افزودن ly ساخته شده و چگونگی صحبت کردن را نشان می‌دهد."),
            ("en", "He drives carefully."),
            ("fa", "carefully از careful ساخته شده است و روش رانندگی را توصیف می‌کند."),
            ("h2", "کاربرد 2: قید مقایسه‌ای"),
            ("en", "She works more carefully than me."),
            ("fa", "برای قیدهای بلند از more پیش از قید استفاده می‌کنیم، نه افزودن er."),
            ("en", "He runs faster than his brother."),
            ("fa", "fast قید کوتاه و بی‌قاعده است و مستقیم er می‌گیرد و به faster تبدیل می‌شود."),
            ("h2", "نکته مهم"),
            ("fa", "بعضی قیدها بی‌قاعده‌اند: good تبدیل به well می‌شود و well در حالت مقایسه‌ای better است. همه صفت‌های ly-دار قید نیستند، مثل friendly که صفت است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Please speak more slowly."),
            ("fa", "more slowly یعنی آهسته‌تر و برای قید بلند slowly درست است."),
            ("en", "She sings well."),
            ("fa", "well قید بی‌قاعده‌ای است که از good ساخته می‌شود."),
        ],
    },

    # ============================ C1/C2 grammar gaps ===========================
    {
        "file": "c1-c2-word-formation.json",
        "name": "Word formation",
        "levelId": 5, "order": 1, "mins": 9,
        "description": "ساخت کلمه با پیشوند و پسوند برای گسترش واژگان.",
        "blocks": [
            ("h1", "ساخت کلمه"),
            ("fa", "بسیاری از کلمات انگلیسی از یک ریشه و افزودن پیشوند یا پسوند ساخته می‌شوند. شناخت این الگوها به درک معنای کلمه‌های ناآشنا و ساختن واژگان تازه کمک زیادی می‌کند."),
            ("h2", "کاربرد 1: پیشوندها برای تغییر معنا"),
            ("en", "It is impossible to finish today."),
            ("fa", "پیشوند im معنای possible را منفی می‌کند. پیشوندهایی مثل un، in و dis هم معنای منفی می‌سازند."),
            ("en", "Please rewrite this paragraph."),
            ("fa", "پیشوند re یعنی دوباره، پس rewrite یعنی دوباره نوشتن."),
            ("h2", "کاربرد 2: پسوندها برای تغییر نوع کلمه"),
            ("en", "Her decision was final."),
            ("fa", "پسوند sion فعل decide را به اسم decision تبدیل کرده است. پسوندها معمولا نوع دستوری کلمه را عوض می‌کنند."),
            ("en", "He acted very carelessly."),
            ("fa", "پسوند less یعنی بدون، و افزودن ly آن را به قید تبدیل کرده است: careless سپس carelessly."),
            ("h2", "نکته مهم"),
            ("fa", "پسوندها معمولا نوع کلمه را تعیین می‌کنند: ness و tion اسم می‌سازند، able و ful صفت، و ly بیشتر قید. این الگوها در آزمون‌های پیشرفته بسیار مهم‌اند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Happiness is important to everyone."),
            ("fa", "پسوند ness صفت happy را به اسم happiness تبدیل کرده است."),
            ("en", "This phone is very useful."),
            ("fa", "پسوند ful صفت می‌سازد و useful یعنی پر از فایده."),
        ],
    },
    {
        "file": "c1-c2-advanced-determiners-and-quantifiers.json",
        "name": "Advanced determiners and quantifiers",
        "levelId": 5, "order": 2, "mins": 9,
        "description": "تعیین‌کننده‌ها و کمیت‌نماهای دقیق در سطح پیشرفته.",
        "blocks": [
            ("h1", "تعیین‌کننده‌های پیشرفته"),
            ("fa", "در سطح پیشرفته انتخاب میان کمیت‌نماهایی مثل few و a few یا much و many معنای دقیق‌تری به جمله می‌دهد. این تفاوت‌های ظریف لحن و دیدگاه گوینده را نشان می‌دهند."),
            ("h2", "کاربرد 1: few و a few"),
            ("en", "Few people understood the lecture."),
            ("fa", "few بار منفی دارد و یعنی تقریبا هیچ‌کس. a few بار مثبت دارد و یعنی تعداد کمی اما کافی."),
            ("en", "A few friends came to help."),
            ("fa", "a few یعنی چند نفر، با نگاهی مثبت. تفاوت آن با few در همین دیدگاه است."),
            ("h2", "کاربرد 2: every، each و all"),
            ("en", "Each student received a certificate."),
            ("fa", "each روی تک‌تک افراد به‌صورت جداگانه تاکید دارد، در حالی که all کل گروه را با هم در نظر می‌گیرد."),
            ("en", "All the seats were taken."),
            ("fa", "all کل مجموعه را در بر می‌گیرد و با اسم جمع یا غیرقابل‌شمارش می‌آید."),
            ("h2", "نکته مهم"),
            ("fa", "few و little برای مفهوم منفی به کار می‌روند، اما a few و a little دیدگاه مثبت دارند. این تفاوت کوچک می‌تواند کل معنای جمله را عوض کند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We have little time left."),
            ("fa", "little بار منفی دارد و یعنی تقریبا هیچ وقتی نمانده است."),
            ("en", "Every answer was correct."),
            ("fa", "every مثل each به تک‌تک موارد اشاره دارد اما نگاهی کلی‌تر به مجموعه دارد."),
        ],
    },

    # ====================== Functional / pragmatics track =====================
    {
        "file": "fn-forms-of-address.json",
        "name": "Forms of address",
        "levelId": 1, "order": 7, "mins": 8,
        "description": "خطاب کردن افراد با عنوان‌هایی مثل Mr و Ms.",
        "blocks": [
            ("h1", "خطاب کردن افراد"),
            ("fa", "در انگلیسی برای خطاب رسمی به افراد از عنوان‌هایی مثل Mr، Mrs، Ms و Miss پیش از نام خانوادگی استفاده می‌کنیم. انتخاب درست عنوان نشانه ادب و احترام است."),
            ("h2", "کاربرد 1: عنوان‌ها برای مردان و زنان"),
            ("en", "Good morning, Mr Brown."),
            ("fa", "Mr برای همه مردان بدون توجه به وضعیت تاهل به کار می‌رود و پیش از نام خانوادگی می‌آید."),
            ("en", "This is Ms Carter."),
            ("fa", "Ms برای زنان به کار می‌رود وقتی نمی‌خواهیم یا نمی‌دانیم که او مجرد است یا متاهل. این امروزه رایج‌ترین و امن‌ترین انتخاب است."),
            ("h2", "کاربرد 2: Mrs و Miss"),
            ("en", "Mrs Smith is my teacher."),
            ("fa", "Mrs برای زن متاهل به کار می‌رود. اگر مطمئن نیستید، بهتر است از Ms استفاده کنید."),
            ("en", "Excuse me, Miss."),
            ("fa", "Miss برای زن مجرد یا دختر جوان است و گاهی به‌تنهایی برای خطاب مودبانه به کار می‌رود."),
            ("h2", "نکته مهم"),
            ("fa", "این عنوان‌ها با نام خانوادگی می‌آیند، نه نام کوچک؛ پس می‌گوییم Mr Brown نه Mr John. برای موقعیت‌های بسیار رسمی یا ناشناس از Sir و Madam استفاده می‌کنیم."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Can I help you, sir?"),
            ("fa", "sir برای خطاب رسمی و مودبانه به یک مرد بدون دانستن نام او به کار می‌رود."),
            ("en", "Thank you, Dr Lee."),
            ("fa", "برای پزشکان و دارندگان دکترا از عنوان Dr پیش از نام خانوادگی استفاده می‌کنیم."),
        ],
    },
    {
        "file": "fn-greetings-and-farewells.json",
        "name": "Greetings and farewells",
        "levelId": 1, "order": 8, "mins": 7,
        "description": "سلام و خداحافظی در موقعیت‌های رسمی و دوستانه.",
        "blocks": [
            ("h1", "سلام و خداحافظی"),
            ("fa", "انتخاب عبارت سلام و خداحافظی به موقعیت بستگی دارد. برخی عبارت‌ها رسمی هستند و برخی دوستانه، و استفاده درست از آن‌ها لحن گفتگو را مشخص می‌کند."),
            ("h2", "کاربرد 1: سلام رسمی و دوستانه"),
            ("en", "Good morning. How are you?"),
            ("fa", "Good morning یک سلام رسمی و مودبانه است که در محیط کار و موقعیت‌های جدی مناسب است."),
            ("en", "Hi! How's it going?"),
            ("fa", "Hi و How's it going دوستانه و غیررسمی هستند و میان دوستان به کار می‌روند."),
            ("h2", "کاربرد 2: خداحافظی"),
            ("en", "Goodbye. Have a nice day."),
            ("fa", "Goodbye رسمی‌تر است و Have a nice day یک پایان مودبانه برای گفتگو فراهم می‌کند."),
            ("en", "See you later!"),
            ("fa", "See you later دوستانه است و یعنی به‌زودی دوباره می‌بینمت."),
            ("h2", "نکته مهم"),
            ("fa", "در موقعیت رسمی از Good morning و Goodbye استفاده کنید و در موقعیت دوستانه از Hi و Bye. هماهنگی لحن سلام و خداحافظی با کل گفتگو مهم است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Nice to meet you."),
            ("fa", "این عبارت هنگام آشنایی برای اولین بار به کار می‌رود."),
            ("en", "Take care!"),
            ("fa", "Take care یک خداحافظی گرم و دوستانه است."),
        ],
    },
    {
        "file": "fn-requests-and-offers.json",
        "name": "Requests and offers",
        "levelId": 2, "order": 6, "mins": 8,
        "description": "درخواست و پیشنهاد مودبانه با can، could و would.",
        "blocks": [
            ("h1", "درخواست و پیشنهاد"),
            ("fa", "برای درخواست کمک یا پیشنهاد دادن از فعل‌های کمکی مثل can، could و would استفاده می‌کنیم. هرچه ساختار مودبانه‌تر باشد، در موقعیت رسمی مناسب‌تر است."),
            ("h2", "کاربرد 1: درخواست مودبانه"),
            ("en", "Could you help me, please?"),
            ("fa", "could از can مودبانه‌تر است و در موقعیت‌های رسمی‌تر مناسب‌تر است. افزودن please ادب بیشتری می‌آورد."),
            ("en", "Would you mind opening the window?"),
            ("fa", "Would you mind یک درخواست بسیار مودبانه است و بعد از آن فعل ing-دار می‌آید."),
            ("h2", "کاربرد 2: پیشنهاد دادن"),
            ("en", "Can I help you?"),
            ("fa", "Can I یک راه ساده برای پیشنهاد کمک است و در گفتگوهای روزمره رایج است."),
            ("en", "Would you like some coffee?"),
            ("fa", "Would you like یک پیشنهاد مودبانه است و از do you want رسمی‌تر و نرم‌تر است."),
            ("h2", "نکته مهم"),
            ("fa", "could و would از can و will مودبانه‌ترند. در موقعیت رسمی از شکل مودبانه استفاده کنید و فراموش نکنید که please لحن را بهتر می‌کند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Shall I carry that for you?"),
            ("fa", "Shall I یک پیشنهاد مودبانه برای کمک کردن است."),
            ("en", "Could I have the menu, please?"),
            ("fa", "Could I یک درخواست مودبانه برای گرفتن چیزی است."),
        ],
    },
    {
        "file": "fn-apologies-and-thanks.json",
        "name": "Apologies and thanks",
        "levelId": 1, "order": 9, "mins": 7,
        "description": "عذرخواهی و تشکر در موقعیت‌های مختلف.",
        "blocks": [
            ("h1", "عذرخواهی و تشکر"),
            ("fa", "عذرخواهی و تشکر بخش مهمی از ادب در گفتگو هستند. عبارت‌های مختلف بسته به جدی بودن موقعیت و میزان رسمی بودن آن انتخاب می‌شوند."),
            ("h2", "کاربرد 1: عذرخواهی"),
            ("en", "I'm sorry I'm late."),
            ("fa", "I'm sorry برای عذرخواهی بابت یک اشتباه یا ناراحتی به کار می‌رود."),
            ("en", "Excuse me, can I get past?"),
            ("fa", "Excuse me برای جلب توجه یا رد شدن از کنار کسی است، نه برای عذرخواهی بابت خطا. این تفاوت مهمی با sorry دارد."),
            ("h2", "کاربرد 2: تشکر و پاسخ"),
            ("en", "Thank you very much."),
            ("fa", "Thank you very much یک تشکر گرم و کمی رسمی است. در موقعیت دوستانه Thanks کافی است."),
            ("en", "You're welcome."),
            ("fa", "You're welcome پاسخ رایج به تشکر است و یعنی خواهش می‌کنم."),
            ("h2", "نکته مهم"),
            ("fa", "Excuse me پیش از مزاحمت یا سوال به کار می‌رود، اما Sorry بعد از خطا یا برای همدردی. این دو را نباید با هم اشتباه گرفت."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "I apologize for the delay."),
            ("fa", "I apologize رسمی‌تر از I'm sorry است و در نامه و محیط کار مناسب است."),
            ("en", "Thanks a lot for your help."),
            ("fa", "Thanks a lot یک تشکر دوستانه و صمیمی است."),
        ],
    },
    {
        "file": "fn-agreeing-and-disagreeing.json",
        "name": "Agreeing and disagreeing",
        "levelId": 3, "order": 4, "mins": 8,
        "description": "موافقت و مخالفت مودبانه در گفتگو و بحث.",
        "blocks": [
            ("h1", "موافقت و مخالفت"),
            ("fa", "در بحث‌ها بیان موافقت یا مخالفت به شکل مودبانه اهمیت زیادی دارد. عبارت‌های نرم به ما کمک می‌کنند بدون ایجاد تنش نظر مخالف خود را بگوییم."),
            ("h2", "کاربرد 1: موافقت"),
            ("en", "I completely agree with you."),
            ("fa", "این عبارت موافقت کامل را نشان می‌دهد و در گفتگوهای رسمی و دوستانه هر دو کاربرد دارد."),
            ("en", "That's a good point."),
            ("fa", "این جمله نشان می‌دهد نظر طرف مقابل را تایید می‌کنیم، حتی اگر کامل با آن موافق نباشیم."),
            ("h2", "کاربرد 2: مخالفت مودبانه"),
            ("en", "I see your point, but I disagree."),
            ("fa", "شروع با I see your point لحن را نرم می‌کند و سپس مخالفت را بیان می‌کنیم. این راه مودبانه‌ای برای مخالفت است."),
            ("en", "I'm not sure I agree with that."),
            ("fa", "این عبارت مخالفت را غیرمستقیم و ملایم بیان می‌کند و از You're wrong بسیار مودبانه‌تر است."),
            ("h2", "نکته مهم"),
            ("fa", "مخالفت مستقیم مثل You're wrong معمولا بی‌ادبانه به نظر می‌رسد. بهتر است ابتدا نظر طرف مقابل را تایید کنید و سپس با but مخالفت خود را بگویید."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Exactly! I think so too."),
            ("fa", "این عبارت موافقت قوی و دوستانه را نشان می‌دهد."),
            ("en", "I'm afraid I can't agree."),
            ("fa", "I'm afraid مخالفت را نرم‌تر و مودبانه‌تر می‌کند."),
        ],
    },
    {
        "file": "fn-email-and-letter-conventions.json",
        "name": "Email and letter conventions",
        "levelId": 4, "order": 1, "mins": 9,
        "description": "آغاز و پایان نامه و ایمیل رسمی و دوستانه.",
        "blocks": [
            ("h1", "قواعد نامه و ایمیل"),
            ("fa", "نامه‌ها و ایمیل‌های رسمی ساختار مشخصی دارند. انتخاب درست عبارت آغاز و پایان نشان می‌دهد که نامه رسمی است یا دوستانه و چقدر مودبانه نوشته شده است."),
            ("h2", "کاربرد 1: آغاز نامه"),
            ("en", "Dear Mr Johnson,"),
            ("fa", "Dear با نام خانوادگی شروع رسمی است. وقتی نام گیرنده را نمی‌دانیم از Dear Sir or Madam استفاده می‌کنیم."),
            ("en", "Hi Sarah,"),
            ("fa", "Hi با نام کوچک یک شروع دوستانه و غیررسمی برای ایمیل میان آشنایان است."),
            ("h2", "کاربرد 2: پایان نامه"),
            ("en", "Yours sincerely, John Smith"),
            ("fa", "Yours sincerely وقتی به کار می‌رود که نامه را با نام گیرنده شروع کرده باشیم. این پایان رسمی است."),
            ("en", "Best regards, Anna"),
            ("fa", "Best regards یک پایان نیمه‌رسمی و رایج برای ایمیل‌های کاری است."),
            ("h2", "نکته مهم"),
            ("fa", "اگر نامه را با Dear Sir or Madam آغاز کردیم، با Yours faithfully پایان می‌دهیم؛ اگر با نام شخص شروع کردیم، Yours sincerely مناسب است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "I am writing to ask about the job."),
            ("fa", "این جمله یک شروع رسمی برای بیان هدف نامه است."),
            ("en", "Looking forward to hearing from you."),
            ("fa", "این عبارت پیش از پایان نامه، انتظار مودبانه برای دریافت پاسخ را نشان می‌دهد."),
        ],
    },

    # ====================== Practical real-world topics =======================
    {
        "file": "rw-numbers-and-prices.json",
        "name": "Numbers and prices",
        "levelId": 1, "order": 10, "mins": 8,
        "description": "خواندن اعداد، قیمت‌ها و مبلغ‌ها با صدای بلند.",
        "blocks": [
            ("h1", "اعداد و قیمت‌ها"),
            ("fa", "خواندن درست اعداد و قیمت‌ها در خرید و گفتگوهای روزمره بسیار کاربردی است. شیوه گفتن قیمت کمی با نوشتن آن فرق دارد و باید الگوی آن را یاد گرفت."),
            ("h2", "کاربرد 1: اعداد بزرگ"),
            ("en", "There are two hundred students."),
            ("fa", "در انگلیسی hundred در حالت عدد بزرگ s نمی‌گیرد، پس می‌گوییم two hundred نه two hundreds."),
            ("en", "The book costs one thousand tomans."),
            ("fa", "thousand هم مثل hundred وقتی با عدد می‌آید جمع بسته نمی‌شود."),
            ("h2", "کاربرد 2: قیمت‌ها"),
            ("en", "It's twenty dollars."),
            ("fa", "برای گفتن قیمت، عدد را پیش از واحد پول می‌گوییم. علامت پول معمولا خوانده نمی‌شود بلکه نام واحد گفته می‌شود."),
            ("en", "That will be fifteen fifty."),
            ("fa", "fifteen fifty یعنی پانزده و پنجاه سنت؛ در گفتار قیمت‌ها اغلب به همین شکل کوتاه خوانده می‌شوند."),
            ("h2", "نکته مهم"),
            ("fa", "hundred، thousand و million وقتی با یک عدد مشخص می‌آیند s نمی‌گیرند، اما در عبارت‌هایی مثل hundreds of people که عدد دقیق ندارند، s می‌گیرند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "How much is this?"),
            ("fa", "این رایج‌ترین سوال برای پرسیدن قیمت یک چیز است."),
            ("en", "It's about fifty euros."),
            ("fa", "about پیش از عدد یعنی «حدودا» و قیمت تقریبی را نشان می‌دهد."),
        ],
    },
    {
        "file": "rw-days-months-seasons.json",
        "name": "Days, months and seasons",
        "levelId": 1, "order": 11, "mins": 7,
        "description": "روزها، ماه‌ها و فصل‌ها و حرف اضافه درست آن‌ها.",
        "blocks": [
            ("h1", "روزها، ماه‌ها و فصل‌ها"),
            ("fa", "نام روزها، ماه‌ها و فصل‌ها در انگلیسی با حرف بزرگ نوشته می‌شوند و هرکدام حرف اضافه مخصوص خود را دارند. دانستن این الگوها برای گفتن تاریخ و برنامه‌ها لازم است."),
            ("h2", "کاربرد 1: روزها با on"),
            ("en", "I have a class on Monday."),
            ("fa", "با روزهای هفته از on استفاده می‌کنیم. نام روزها همیشه با حرف بزرگ نوشته می‌شوند."),
            ("en", "We rest on Friday."),
            ("fa", "on Friday یعنی در روز جمعه. این حرف اضافه برای همه روزهای هفته یکسان است."),
            ("h2", "کاربرد 2: ماه‌ها و فصل‌ها با in"),
            ("en", "My holiday is in July."),
            ("fa", "با ماه‌ها از in استفاده می‌کنیم. نام ماه‌ها هم با حرف بزرگ نوشته می‌شوند."),
            ("en", "It snows in winter."),
            ("fa", "با فصل‌ها هم از in استفاده می‌کنیم، پس in winter درست است."),
            ("h2", "نکته مهم"),
            ("fa", "قانون ساده: on برای روزها، in برای ماه‌ها و فصل‌ها. بر خلاف فارسی، در انگلیسی روزها و ماه‌ها همیشه با حرف بزرگ شروع می‌شوند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "School starts in September."),
            ("fa", "in با ماه September به کار رفته است."),
            ("en", "See you on Sunday."),
            ("fa", "on با روز Sunday درست است."),
        ],
    },
    {
        "file": "rw-telling-the-time.json",
        "name": "Telling the time",
        "levelId": 1, "order": 12, "mins": 8,
        "description": "گفتن ساعت با o'clock، past و to.",
        "blocks": [
            ("h1", "گفتن ساعت"),
            ("fa", "برای گفتن ساعت در انگلیسی چند الگوی رایج وجود دارد. می‌توان عدد ساعت و دقیقه را مستقیم گفت یا از کلمه‌های past و to برای بیان دقیقه‌ها استفاده کرد."),
            ("h2", "کاربرد 1: ساعت‌های کامل و past"),
            ("en", "It's three o'clock."),
            ("fa", "o'clock فقط برای ساعت‌های کامل و بدون دقیقه به کار می‌رود."),
            ("en", "It's ten past four."),
            ("fa", "past یعنی «گذشته از»؛ پس ten past four یعنی چهار و ده دقیقه."),
            ("h2", "کاربرد 2: to و نیم‌ساعت"),
            ("en", "It's quarter to nine."),
            ("fa", "to یعنی «مانده به»؛ quarter to nine یعنی یک ربع به نه، یا هشت و چهل‌وپنج دقیقه."),
            ("en", "It's half past six."),
            ("fa", "half past six یعنی شش و نیم. half past برای دقیقه سی به کار می‌رود."),
            ("h2", "نکته مهم"),
            ("fa", "از ابتدای ساعت تا دقیقه سی از past استفاده می‌کنیم و بعد از آن از to برای ساعت بعدی. در گفتار روزمره می‌توان ساده گفت: it's six thirty."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "What time is it?"),
            ("fa", "این رایج‌ترین سوال برای پرسیدن ساعت است."),
            ("en", "The train leaves at noon."),
            ("fa", "noon یعنی ظهر یا ساعت دوازده روز و midnight یعنی نیمه‌شب."),
        ],
    },
    {
        "file": "rw-the-alphabet-and-spelling.json",
        "name": "The alphabet and spelling",
        "levelId": 1, "order": 13, "mins": 7,
        "description": "هجی کردن کلمه‌ها و گفتن حروف با صدای بلند.",
        "blocks": [
            ("h1", "هجی کردن"),
            ("fa", "گاهی لازم است نام یا کلمه‌ای را حرف‌به‌حرف بگوییم، مثلا هنگام پر کردن فرم یا پشت تلفن. برای این کار باید نام درست حروف الفبا را بلد باشیم."),
            ("h2", "کاربرد 1: درخواست هجی کردن"),
            ("en", "How do you spell your name?"),
            ("fa", "این سوال رایج برای درخواست هجی کردن یک کلمه یا نام است."),
            ("en", "It's S-A-R-A."),
            ("fa", "برای پاسخ، حروف را یکی‌یکی نام می‌بریم. هر حرف نام مخصوص خود را دارد."),
            ("h2", "کاربرد 2: حروف تکراری"),
            ("en", "My name is Anna, double N."),
            ("fa", "وقتی یک حرف دو بار پشت سر هم می‌آید، می‌توان به‌جای تکرار گفت double و سپس نام حرف."),
            ("en", "It's spelled with a capital B."),
            ("fa", "capital یعنی حرف بزرگ. برای حرف کوچک می‌گوییم small یا lowercase."),
            ("h2", "نکته مهم"),
            ("fa", "نام حروف با صدای آن‌ها فرق دارد؛ مثلا حرف W را double-u می‌خوانیم. تمرین گفتن نام حروف برای مکالمه تلفنی بسیار مفید است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Could you spell that, please?"),
            ("fa", "یک درخواست مودبانه برای هجی کردن دوباره یک کلمه است."),
            ("en", "That's two words."),
            ("fa", "این عبارت توضیح می‌دهد که نوشته باید در دو کلمه جدا نوشته شود."),
        ],
    },
    {
        "file": "rw-contractions.json",
        "name": "Common contractions",
        "levelId": 1, "order": 14, "mins": 7,
        "description": "شکل کوتاه‌شده فعل‌ها مثل I'm و don't.",
        "blocks": [
            ("h1", "شکل کوتاه‌شده"),
            ("fa", "در گفتار و نوشتار دوستانه، بسیاری از فعل‌ها به شکل کوتاه‌شده با آپاستروف می‌آیند. شناخت این شکل‌ها برای درک مکالمه طبیعی ضروری است."),
            ("h2", "کاربرد 1: کوتاه‌شده فعل be"),
            ("en", "I'm a teacher."),
            ("fa", "I'm شکل کوتاه‌شده I am است. آپاستروف جای حرف حذف‌شده a را می‌گیرد."),
            ("en", "She's at home."),
            ("fa", "She's می‌تواند کوتاه‌شده she is یا she has باشد و معنا از جمله مشخص می‌شود."),
            ("h2", "کاربرد 2: کوتاه‌شده منفی"),
            ("en", "I don't know."),
            ("fa", "don't شکل کوتاه‌شده do not است و در گفتار بسیار رایج‌تر از شکل کامل است."),
            ("en", "He can't come today."),
            ("fa", "can't کوتاه‌شده cannot است. در منفی فعل‌های کمکی، not به not' کوتاه می‌شود."),
            ("h2", "نکته مهم"),
            ("fa", "شکل کوتاه‌شده برای گفتار و نوشتار دوستانه مناسب است، اما در نوشتار بسیار رسمی بهتر است شکل کامل به کار رود. اشتباه رایج، نوشتن its به‌جای it's است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "They're my friends."),
            ("fa", "They're کوتاه‌شده they are است."),
            ("en", "We'll see you soon."),
            ("fa", "We'll کوتاه‌شده we will است و l جای will حذف‌شده را نشان می‌دهد."),
        ],
    },
    {
        "file": "rw-punctuation-and-capitalization.json",
        "name": "Punctuation and capitalization",
        "levelId": 2, "order": 7, "mins": 8,
        "description": "قواعد پایه نقطه‌گذاری و حرف بزرگ در نوشتار.",
        "blocks": [
            ("h1", "نقطه‌گذاری و حرف بزرگ"),
            ("fa", "نوشتار درست انگلیسی قواعد مشخصی برای نقطه‌گذاری و استفاده از حرف بزرگ دارد. رعایت این قواعد متن را خواناتر و حرفه‌ای‌تر می‌کند."),
            ("h2", "کاربرد 1: حرف بزرگ"),
            ("en", "My friend John lives in London."),
            ("fa", "حرف اول جمله، نام اشخاص و نام مکان‌ها همیشه با حرف بزرگ نوشته می‌شوند."),
            ("en", "We met on Monday in May."),
            ("fa", "نام روزها و ماه‌ها هم با حرف بزرگ شروع می‌شوند، بر خلاف فصل‌ها که معمولا حرف کوچک دارند."),
            ("h2", "کاربرد 2: علامت‌های پایان جمله"),
            ("en", "Where do you live?"),
            ("fa", "جمله پرسشی با علامت سوال پایان می‌یابد. جمله خبری با نقطه و جمله با احساس قوی با علامت تعجب."),
            ("en", "Watch out!"),
            ("fa", "علامت تعجب برای هشدار یا احساس قوی به کار می‌رود، اما نباید زیاد استفاده شود."),
            ("h2", "نکته مهم"),
            ("fa", "ضمیر I همیشه با حرف بزرگ نوشته می‌شود، حتی در وسط جمله. این یکی از تفاوت‌های مهم نوشتار انگلیسی است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "She speaks English and French."),
            ("fa", "نام زبان‌ها و ملیت‌ها هم با حرف بزرگ نوشته می‌شوند."),
            ("en", "I think it's a good idea."),
            ("fa", "ضمیر I با حرف بزرگ آمده و جمله با نقطه پایان یافته است."),
        ],
    },

    # ============================ More grammar topics =========================
    {
        "file": "a2-ed-and-ing-adjectives.json",
        "name": "-ed and -ing adjectives",
        "levelId": 2, "order": 8, "mins": 7,
        "description": "تفاوت صفت‌های ed-دار و ing-دار مثل bored و boring.",
        "blocks": [
            ("h1", "صفت‌های ed و ing"),
            ("fa", "بسیاری از صفت‌ها دو شکل دارند: یکی با ed و یکی با ing. شکل ed احساس شخص را نشان می‌دهد و شکل ing ویژگی چیزی که آن احساس را ایجاد می‌کند. اشتباه گرفتن این دو یکی از خطاهای رایج است."),
            ("h2", "کاربرد 1: شکل ed برای احساس"),
            ("en", "I am bored."),
            ("fa", "bored احساس خود شخص را نشان می‌دهد، یعنی من حوصله‌ام سر رفته است. صفت ed-دار همیشه درباره فردی است که چیزی را حس می‌کند."),
            ("en", "She was tired after work."),
            ("fa", "tired احساس او را بیان می‌کند. این شکل ed همیشه به یک موجود زنده با احساس برمی‌گردد."),
            ("h2", "کاربرد 2: شکل ing برای علت"),
            ("en", "This book is boring."),
            ("fa", "boring ویژگی کتاب را نشان می‌دهد، یعنی کتاب باعث بی‌حوصلگی می‌شود. شکل ing درباره چیزی است که احساس را ایجاد می‌کند."),
            ("en", "The film was exciting."),
            ("fa", "exciting یعنی فیلم هیجان ایجاد می‌کند. اگر بگوییم I was excited یعنی خودمان هیجان‌زده شدیم."),
            ("h2", "نکته مهم"),
            ("fa", "یک قانون ساده: people are ed و things are ing. اگر بگویید I am boring یعنی شما برای دیگران خسته‌کننده هستید، نه اینکه حوصله‌تان سر رفته است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "I'm interested in history."),
            ("fa", "interested احساس شخص را نشان می‌دهد."),
            ("en", "The lesson was interesting."),
            ("fa", "interesting ویژگی درس را بیان می‌کند که علاقه ایجاد می‌کند."),
        ],
    },
    {
        "file": "a2-must-have-to-should.json",
        "name": "Must, have to and should",
        "levelId": 2, "order": 9, "mins": 8,
        "description": "تفاوت اجبار و توصیه با must، have to و should.",
        "blocks": [
            ("h1", "اجبار و توصیه"),
            ("fa", "must، have to و should هر سه درباره لزوم انجام کار صحبت می‌کنند، اما شدت و منبع آن فرق دارد. must و have to اجبار قوی هستند و should فقط یک توصیه است."),
            ("h2", "کاربرد 1: اجبار با must و have to"),
            ("en", "You must wear a seatbelt."),
            ("fa", "must یک اجبار قوی است که اغلب از نظر خود گوینده یا یک قانون می‌آید."),
            ("en", "I have to work on Saturday."),
            ("fa", "have to هم اجبار است اما بیشتر به قانون یا شرایط بیرونی اشاره دارد، نه نظر شخصی گوینده."),
            ("h2", "کاربرد 2: توصیه با should"),
            ("en", "You should see a doctor."),
            ("fa", "should فقط یک توصیه یا نظر است، نه اجبار. شخص آزاد است که آن را انجام دهد یا ندهد."),
            ("en", "We should leave early."),
            ("fa", "should اینجا یک پیشنهاد منطقی است، نه یک الزام قطعی."),
            ("h2", "نکته مهم"),
            ("fa", "نکته مهم در منفی است: mustn't یعنی ممنوع است، اما don't have to یعنی لازم نیست. این دو معنای کاملا متفاوتی دارند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "You mustn't smoke here."),
            ("fa", "mustn't یعنی این کار ممنوع است."),
            ("en", "You don't have to come if you're tired."),
            ("fa", "don't have to یعنی اجباری نیست، اما اگر بخواهی می‌توانی بیایی."),
        ],
    },
    {
        "file": "a2-some-any-no-compounds.json",
        "name": "Some, any and no compounds",
        "levelId": 2, "order": 10, "mins": 7,
        "description": "ترکیب‌هایی مثل something، anywhere و nobody.",
        "blocks": [
            ("h1", "ترکیب‌های some، any و no"),
            ("fa", "از some، any و no می‌توان ترکیب‌هایی با thing، one، body و where ساخت. این کلمه‌ها به چیز، شخص یا مکان نامشخص اشاره می‌کنند و قاعده آن‌ها شبیه some و any است."),
            ("h2", "کاربرد 1: some-ترکیب‌ها در جمله مثبت"),
            ("en", "There is something on the table."),
            ("fa", "something در جمله مثبت به کار می‌رود و به یک چیز نامشخص اشاره دارد."),
            ("en", "Someone is at the door."),
            ("fa", "someone به یک شخص نامشخص اشاره دارد و در جمله مثبت رایج است."),
            ("h2", "کاربرد 2: any-ترکیب‌ها در منفی و سوال"),
            ("en", "I can't find anything."),
            ("fa", "anything در جمله منفی و سوالی به کار می‌رود. اینجا یعنی هیچ چیزی پیدا نمی‌کنم."),
            ("en", "Is there anyone here?"),
            ("fa", "anyone در سوال‌ها استفاده می‌شود و به یک شخص نامشخص اشاره دارد."),
            ("h2", "نکته مهم"),
            ("fa", "no-ترکیب‌ها مثل nothing و nobody خودشان معنای منفی دارند، پس فعل جمله باید مثبت بماند: I saw nobody، نه I didn't see nobody."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Let's go somewhere quiet."),
            ("fa", "somewhere به یک مکان نامشخص در جمله مثبت اشاره دارد."),
            ("en", "Nobody answered the phone."),
            ("fa", "nobody معنای منفی دارد، پس فعل answered مثبت مانده است."),
        ],
    },
    {
        "file": "a2-adjective-order.json",
        "name": "Adjective order",
        "levelId": 2, "order": 11, "mins": 7,
        "description": "ترتیب درست چند صفت پیش از یک اسم.",
        "blocks": [
            ("h1", "ترتیب صفت‌ها"),
            ("fa", "وقتی چند صفت پیش از یک اسم می‌آیند، ترتیب آن‌ها در انگلیسی قاعده‌مند است. معمولا نظر و کیفیت اول می‌آید و سپس اندازه، سن، رنگ و جنس."),
            ("h2", "کاربرد 1: نظر پیش از واقعیت"),
            ("en", "a beautiful old house"),
            ("fa", "beautiful یک نظر است و پیش از old که سن را نشان می‌دهد می‌آید. صفت‌های نظری همیشه اول می‌آیند."),
            ("en", "a nice big garden"),
            ("fa", "nice نظر است و big اندازه، پس nice زودتر آمده است."),
            ("h2", "کاربرد 2: اندازه، رنگ و جنس"),
            ("en", "a small black bag"),
            ("fa", "اندازه (small) پیش از رنگ (black) می‌آید. این ترتیب در انگلیسی تقریبا ثابت است."),
            ("en", "a long red wooden table"),
            ("fa", "ترتیب اندازه، رنگ و سپس جنس رعایت شده است: long، red، wooden."),
            ("h2", "نکته مهم"),
            ("fa", "یک ترتیب کلی پرکاربرد: نظر، اندازه، سن، رنگ، جنس و سپس اسم. وقتی بیش از سه صفت داریم، معمولا جمله را بازنویسی می‌کنیم تا طبیعی‌تر شود."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "an expensive Italian car"),
            ("fa", "expensive نظر است و Italian منشا، پس به ترتیب درست آمده‌اند."),
            ("en", "a big round table"),
            ("fa", "اندازه (big) پیش از شکل (round) قرار گرفته است."),
        ],
    },
    {
        "file": "a2-prepositions-of-movement.json",
        "name": "Prepositions of movement",
        "levelId": 2, "order": 12, "mins": 7,
        "description": "حروف اضافه حرکت مثل to، into و through.",
        "blocks": [
            ("h1", "حروف اضافه حرکت"),
            ("fa", "حروف اضافه حرکت جهت یا مسیر یک حرکت را نشان می‌دهند، بر خلاف حروف اضافه مکان که فقط موقعیت ثابت را بیان می‌کنند. مهم‌ترین آن‌ها to، into، out of و through هستند."),
            ("h2", "کاربرد 1: to و into"),
            ("en", "I'm going to the office."),
            ("fa", "to جهت حرکت به سمت یک مقصد را نشان می‌دهد."),
            ("en", "She walked into the room."),
            ("fa", "into حرکت به داخل یک فضای بسته را بیان می‌کند، نه فقط جهت کلی."),
            ("h2", "کاربرد 2: through و across"),
            ("en", "We drove through the tunnel."),
            ("fa", "through یعنی از داخل و از یک سر تا سر دیگر چیزی عبور کردن."),
            ("en", "He ran across the street."),
            ("fa", "across یعنی از این سو به آن سوی یک سطح یا خط رفتن."),
            ("h2", "نکته مهم"),
            ("fa", "تفاوت مهم با حروف مکان این است: in یک موقعیت ثابت را نشان می‌دهد اما into حرکت به داخل را. همچنین معمولا می‌گوییم go home بدون حرف اضافه to."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "The cat jumped onto the sofa."),
            ("fa", "onto حرکت به روی یک سطح را نشان می‌دهد."),
            ("en", "They came out of the building."),
            ("fa", "out of حرکت از داخل به بیرون را بیان می‌کند."),
        ],
    },
    {
        "file": "b1-dependent-prepositions.json",
        "name": "Dependent prepositions",
        "levelId": 3, "order": 5, "mins": 8,
        "description": "حرف اضافه ثابت پس از صفت‌ها و فعل‌ها مثل good at.",
        "blocks": [
            ("h1", "حرف اضافه وابسته"),
            ("fa", "بعضی صفت‌ها و فعل‌ها همیشه با یک حرف اضافه مشخص می‌آیند. این ترکیب‌ها قاعده روشنی ندارند و باید آن‌ها را با هم به‌صورت یک واحد یاد گرفت."),
            ("h2", "کاربرد 1: صفت + حرف اضافه"),
            ("en", "She is good at math."),
            ("fa", "صفت good همیشه با حرف اضافه at می‌آید. این ترکیب ثابت است و قابل تغییر نیست."),
            ("en", "I'm afraid of spiders."),
            ("fa", "afraid همیشه با of می‌آید. این یک نمونه رایج از صفت و حرف اضافه وابسته است."),
            ("h2", "کاربرد 2: فعل + حرف اضافه"),
            ("en", "He depends on his parents."),
            ("fa", "فعل depend همیشه با on می‌آید. تغییر حرف اضافه جمله را نادرست می‌کند."),
            ("en", "We are waiting for the bus."),
            ("fa", "فعل wait با حرف اضافه for همراه است وقتی منتظر چیزی هستیم."),
            ("h2", "نکته مهم"),
            ("fa", "بعد از حرف اضافه همیشه اسم یا فعل ing-دار می‌آید، نه شکل ساده فعل: interested in learning، نه interested in learn."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "She's interested in art."),
            ("fa", "interested همیشه با in می‌آید."),
            ("en", "Thank you for your help."),
            ("fa", "ترکیب ثابت thank someone for یعنی تشکر بابت چیزی."),
        ],
    },
    {
        "file": "b1-indirect-questions.json",
        "name": "Indirect questions",
        "levelId": 3, "order": 6, "mins": 8,
        "description": "سوال‌های غیرمستقیم مودبانه با ترتیب جمله خبری.",
        "blocks": [
            ("h1", "سوال غیرمستقیم"),
            ("fa", "سوال غیرمستقیم راهی مودبانه‌تر برای پرسیدن است که با عبارت‌هایی مثل Could you tell me یا Do you know شروع می‌شود. نکته کلیدی این است که ترتیب کلمات بعد از آن مثل جمله خبری می‌شود."),
            ("h2", "کاربرد 1: تغییر ترتیب کلمات"),
            ("en", "Do you know where the station is?"),
            ("fa", "در سوال مستقیم می‌گفتیم where is the station، اما در سوال غیرمستقیم فعل is بعد از فاعل می‌آید، مثل جمله خبری."),
            ("en", "Could you tell me what time it is?"),
            ("fa", "اینجا هم بعد از what از ترتیب خبری it is استفاده شده، نه is it."),
            ("h2", "کاربرد 2: سوال بله یا خیر با if"),
            ("en", "Do you know if the shop is open?"),
            ("fa", "وقتی سوال اصلی بله یا خیر است، از if یا whether استفاده می‌کنیم و سپس ترتیب خبری می‌آید."),
            ("en", "I wonder if she will come."),
            ("fa", "if جمله را به سوال غیرمستقیم تبدیل کرده و فعل به شکل خبری مانده است."),
            ("h2", "نکته مهم"),
            ("fa", "در سوال غیرمستقیم از do و does کمکی استفاده نمی‌کنیم: Do you know where he lives، نه where does he live. این مهم‌ترین تفاوت با سوال مستقیم است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Can you tell me how this works?"),
            ("fa", "بعد از how از ترتیب خبری this works استفاده شده است."),
            ("en", "I'd like to know why he left."),
            ("fa", "بعد از why ترتیب خبری he left آمده، نه did he leave."),
        ],
    },
    {
        "file": "b1-future-time-clauses.json",
        "name": "Future time clauses",
        "levelId": 3, "order": 7, "mins": 8,
        "description": "جمله‌های زمان آینده با when و as soon as.",
        "blocks": [
            ("h1", "جمله‌های زمان آینده"),
            ("fa", "وقتی درباره آینده با کلمه‌هایی مثل when، as soon as، before و after صحبت می‌کنیم، در آن بخش از جمله از حال ساده استفاده می‌کنیم، نه will. این یک قانون مهم و پرکاربرد است."),
            ("h2", "کاربرد 1: when و as soon as"),
            ("en", "I'll call you when I arrive."),
            ("fa", "بعد از when فعل arrive به شکل حال ساده آمده، هرچند درباره آینده صحبت می‌کنیم. will فقط در بخش اصلی جمله می‌آید."),
            ("en", "As soon as he comes, we'll start."),
            ("fa", "بعد از as soon as از comes استفاده شده، نه will come. این الگوی ثابت جمله‌های زمان آینده است."),
            ("h2", "کاربرد 2: before و after"),
            ("en", "I'll finish before they arrive."),
            ("fa", "بعد از before فعل arrive به شکل حال ساده مانده است، با اینکه به آینده اشاره دارد."),
            ("en", "We'll eat after the film ends."),
            ("fa", "بعد از after از ends استفاده شده، نه will end."),
            ("h2", "نکته مهم"),
            ("fa", "قانون کلیدی: بعد از when، as soon as، before و after درباره آینده، از حال ساده استفاده می‌کنیم و will را فقط در بخش اصلی جمله می‌آوریم."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "When it stops raining, we'll go out."),
            ("fa", "بعد از when فعل stops به شکل حال ساده است."),
            ("en", "I'll wait until you are ready."),
            ("fa", "بعد از until هم از حال ساده are استفاده می‌کنیم، نه will be."),
        ],
    },

    # ========================= Pronunciation track ============================
    {
        "file": "pr-ed-ending-pronunciation.json",
        "name": "Pronouncing -ed endings",
        "levelId": 2, "order": 13, "mins": 7,
        "description": "سه تلفظ مختلف پایانه ed در فعل‌های گذشته.",
        "blocks": [
            ("h1", "تلفظ پایانه ed"),
            ("fa", "پایانه ed در فعل‌های باقاعده گذشته همیشه یکسان تلفظ نمی‌شود. سه تلفظ وجود دارد و انتخاب آن به صدای پایانی فعل اصلی بستگی دارد، نه به نوشتار."),
            ("h2", "کاربرد 1: صدای t و d"),
            ("en", "worked, helped, asked"),
            ("fa", "اگر فعل با صدای بی‌واک مثل k یا p تمام شود، ed مثل t تلفظ می‌شود، پس worked شبیه workt شنیده می‌شود."),
            ("en", "played, lived, called"),
            ("fa", "اگر فعل با صدای واک‌دار یا حرف صدادار تمام شود، ed مثل d تلفظ می‌شود."),
            ("h2", "کاربرد 2: صدای id"),
            ("en", "wanted, needed, started"),
            ("fa", "فقط وقتی فعل با صدای t یا d تمام شود، ed یک هجای جدا با صدای id می‌سازد، مثل wanted که دو هجا دارد."),
            ("en", "decided, visited"),
            ("fa", "چون decide با صدای d تمام می‌شود، ed به‌صورت id و یک هجای اضافه تلفظ می‌شود."),
            ("h2", "نکته مهم"),
            ("fa", "فقط فعل‌هایی که با t یا d تمام می‌شوند یک هجای اضافه می‌گیرند. بقیه فعل‌ها هجای تازه نمی‌گیرند، پس worked هنوز یک هجاست."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "stopped sounds like 'stopt'"),
            ("fa", "چون stop با صدای p تمام می‌شود، ed مثل t تلفظ می‌شود."),
            ("en", "ended has two syllables"),
            ("fa", "end با صدای d تمام می‌شود، پس ended دو هجا با صدای id دارد."),
        ],
    },
    {
        "file": "pr-plural-s-pronunciation.json",
        "name": "Pronouncing plural -s",
        "levelId": 1, "order": 15, "mins": 7,
        "description": "سه تلفظ مختلف پایانه s در اسم‌های جمع.",
        "blocks": [
            ("h1", "تلفظ پایانه s"),
            ("fa", "پایانه s در اسم‌های جمع و فعل‌های سوم شخص سه تلفظ دارد: s، z و iz. مثل پایانه ed، انتخاب درست به صدای پایانی کلمه بستگی دارد."),
            ("h2", "کاربرد 1: صدای s و z"),
            ("en", "books, cats, maps"),
            ("fa", "اگر کلمه با صدای بی‌واک مثل k، t یا p تمام شود، s مثل s تلفظ می‌شود."),
            ("en", "dogs, pens, cars"),
            ("fa", "اگر کلمه با صدای واک‌دار یا حرف صدادار تمام شود، s مثل z تلفظ می‌شود، پس dogs شبیه dogz شنیده می‌شود."),
            ("h2", "کاربرد 2: صدای iz"),
            ("en", "buses, boxes, watches"),
            ("fa", "وقتی کلمه با صداهای s، z، ch یا sh تمام شود، s یک هجای جدا با صدای iz می‌سازد."),
            ("en", "pages, glasses"),
            ("fa", "چون این کلمه‌ها با صدای زمزمه‌ای تمام می‌شوند، s به‌صورت iz و یک هجای اضافه تلفظ می‌شود."),
            ("h2", "نکته مهم"),
            ("fa", "همین سه قانون برای فعل سوم شخص مفرد هم درست است: watches با iz و runs با z تلفظ می‌شود."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "cups sounds like 's'"),
            ("fa", "چون cup با صدای p تمام می‌شود، s مثل s تلفظ می‌شود."),
            ("en", "boxes has an extra syllable"),
            ("fa", "box با صدای x تمام می‌شود، پس boxes یک هجای اضافه با iz می‌گیرد."),
        ],
    },
    {
        "file": "pr-word-stress.json",
        "name": "Word stress",
        "levelId": 2, "order": 14, "mins": 8,
        "description": "تاکید روی هجای درست در کلمه‌های چندهجایی.",
        "blocks": [
            ("h1", "تاکید کلمه"),
            ("fa", "در کلمه‌های انگلیسی چندهجایی، یک هجا قوی‌تر و بلندتر تلفظ می‌شود. تاکید درست برای فهمیده شدن بسیار مهم است و گاهی حتی معنای کلمه را عوض می‌کند."),
            ("h2", "کاربرد 1: جای تاکید"),
            ("en", "WA-ter, TA-ble, HAP-py"),
            ("fa", "در بسیاری از کلمه‌های دوهجایی، تاکید روی هجای اول است. هجای قوی بلندتر و واضح‌تر گفته می‌شود."),
            ("en", "ho-TEL, a-BOUT, be-GIN"),
            ("fa", "در بعضی کلمه‌ها تاکید روی هجای دوم می‌افتد. این جای تاکید را باید همراه کلمه یاد گرفت."),
            ("h2", "کاربرد 2: تاکید معنا را عوض می‌کند"),
            ("en", "a REcord (noun) / to reCORD (verb)"),
            ("fa", "بعضی کلمه‌ها بسته به جای تاکید اسم یا فعل می‌شوند. record با تاکید اول اسم و با تاکید دوم فعل است."),
            ("en", "a PREsent / to preSENT"),
            ("fa", "همین الگو برای present هم درست است؛ تاکید جای کلمه را در جمله مشخص می‌کند."),
            ("h2", "نکته مهم"),
            ("fa", "در بسیاری از اسم‌های دوهجایی تاکید روی هجای اول و در فعل‌ها روی هجای دوم است. شنیدن و تکرار بهترین راه یادگیری تاکید درست است."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "comPUTer has stress on the second syllable"),
            ("fa", "در computer تاکید روی هجای دوم است."),
            ("en", "BANana / baNAna"),
            ("fa", "در banana تاکید روی هجای میانی است؛ جای اشتباه تاکید فهم را سخت می‌کند."),
        ],
    },
    {
        "file": "pr-schwa-and-weak-forms.json",
        "name": "The schwa and weak forms",
        "levelId": 3, "order": 8, "mins": 8,
        "description": "صدای ضعیف schwa در هجاهای بدون تاکید.",
        "blocks": [
            ("h1", "صدای schwa و شکل ضعیف"),
            ("fa", "رایج‌ترین صدای انگلیسی، صدای کوتاه و ضعیف schwa است که در هجاهای بدون تاکید شنیده می‌شود. بسیاری از کلمه‌های کوچک در گفتار طبیعی به شکل ضعیف تلفظ می‌شوند."),
            ("h2", "کاربرد 1: schwa در کلمه‌ها"),
            ("en", "about, banana, teacher"),
            ("fa", "حرف‌های بدون تاکید در این کلمه‌ها صدای ضعیف schwa می‌گیرند، نه صدای کامل خود حرف."),
            ("en", "the first 'a' in 'about' is a schwa"),
            ("fa", "این صدا خیلی کوتاه و آرام است و تقریبا مثل یک «اِ» بسیار ضعیف شنیده می‌شود."),
            ("h2", "کاربرد 2: شکل ضعیف کلمه‌های کوچک"),
            ("en", "a cup of tea (of sounds like 'uv')"),
            ("fa", "کلمه‌های کوچک مثل of، to و and در گفتار طبیعی ضعیف می‌شوند و صدای schwa می‌گیرند."),
            ("en", "fish and chips (and sounds like 'n')"),
            ("fa", "and در گفتار روزمره تقریبا به یک صدای کوتاه n کاهش می‌یابد."),
            ("h2", "نکته مهم"),
            ("fa", "تلفظ کامل همه کلمه‌ها گفتار را غیرطبیعی می‌کند. تلفظ ضعیف کلمه‌های کوچک و استفاده از schwa باعث می‌شود انگلیسی روان‌تر و طبیعی‌تر شنیده شود."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "I can go (can sounds like 'kn')"),
            ("fa", "can در جمله مثبت معمولا ضعیف و کوتاه تلفظ می‌شود."),
            ("en", "a piece of cake"),
            ("fa", "of با صدای schwa و بسیار کوتاه گفته می‌شود."),
        ],
    },
    {
        "file": "pr-intonation-basics.json",
        "name": "Intonation basics",
        "levelId": 3, "order": 9, "mins": 7,
        "description": "بالا و پایین رفتن صدا در سوال‌ها و جمله‌ها.",
        "blocks": [
            ("h1", "آهنگ کلام"),
            ("fa", "آهنگ کلام یعنی بالا و پایین رفتن صدا هنگام صحبت. این آهنگ معنا و احساس را منتقل می‌کند و گاهی تفاوت میان سوال و جمله خبری را مشخص می‌سازد."),
            ("h2", "کاربرد 1: صدای پایین‌رونده"),
            ("en", "Where do you live? (falling)"),
            ("fa", "در سوال‌های اطلاعاتی با کلمه پرسشی، صدا معمولا در پایان پایین می‌آید."),
            ("en", "I live in Tehran. (falling)"),
            ("fa", "جمله‌های خبری معمولی هم با آهنگ پایین‌رونده تمام می‌شوند که نشانه قطعیت است."),
            ("h2", "کاربرد 2: صدای بالارونده"),
            ("en", "Are you ready? (rising)"),
            ("fa", "در سوال‌های بله یا خیر، صدا در پایان بالا می‌رود. این آهنگ نشانه سوال بودن است."),
            ("en", "Really? (rising)"),
            ("fa", "آهنگ بالارونده می‌تواند تعجب یا تردید را هم نشان دهد."),
            ("h2", "نکته مهم"),
            ("fa", "قانون کلی: سوال‌های بله یا خیر آهنگ بالارونده دارند، اما سوال‌های با کلمه پرسشی و جمله‌های خبری آهنگ پایین‌رونده. آهنگ درست لحن مودبانه و طبیعی می‌سازد."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Do you like it? (rising)"),
            ("fa", "این سوال بله یا خیر است، پس آهنگ بالا می‌رود."),
            ("en", "What's your name? (falling)"),
            ("fa", "این سوال با کلمه پرسشی است، پس آهنگ پایین می‌آید."),
        ],
    },

    # ===================== More functional / pragmatics =======================
    {
        "file": "fn-making-suggestions.json",
        "name": "Making suggestions",
        "levelId": 2, "order": 15, "mins": 7,
        "description": "پیشنهاد دادن با Why don't we و How about.",
        "blocks": [
            ("h1", "پیشنهاد دادن"),
            ("fa", "برای پیشنهاد دادن چند ساختار رایج وجود دارد. هرکدام لحن کمی متفاوت دارند و بعضی با فعل ساده و بعضی با فعل ing-دار می‌آیند."),
            ("h2", "کاربرد 1: Why don't و Let's"),
            ("en", "Why don't we go out tonight?"),
            ("fa", "Why don't we یک پیشنهاد دوستانه است و بعد از آن فعل ساده می‌آید."),
            ("en", "Let's take a break."),
            ("fa", "Let's یک پیشنهاد گروهی است که خود گوینده هم در آن شرکت دارد و با فعل ساده می‌آید."),
            ("h2", "کاربرد 2: How about و Shall we"),
            ("en", "How about going to the cinema?"),
            ("fa", "بعد از How about فعل ing-دار می‌آید، نه فعل ساده. این یک تفاوت ساختاری مهم است."),
            ("en", "Shall we start now?"),
            ("fa", "Shall we یک پیشنهاد مودبانه است و بیشتر در موقعیت‌های کمی رسمی‌تر به کار می‌رود."),
            ("h2", "نکته مهم"),
            ("fa", "بعد از How about و What about فعل ing-دار می‌آید، اما بعد از Why don't we و Let's فعل ساده. توجه به این تفاوت از اشتباه‌های رایج جلوگیری می‌کند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "We could try the new restaurant."),
            ("fa", "could هم یک راه نرم برای پیشنهاد دادن است."),
            ("en", "What about meeting at six?"),
            ("fa", "بعد از What about فعل meeting به شکل ing-دار آمده است."),
        ],
    },
    {
        "file": "fn-asking-for-clarification.json",
        "name": "Asking for clarification",
        "levelId": 2, "order": 16, "mins": 7,
        "description": "درخواست تکرار یا توضیح هنگام نفهمیدن.",
        "blocks": [
            ("h1", "درخواست توضیح"),
            ("fa", "وقتی چیزی را نمی‌فهمیم یا نمی‌شنویم، باید مودبانه درخواست تکرار یا توضیح کنیم. عبارت‌های مناسب این کار را آسان و طبیعی می‌کنند."),
            ("h2", "کاربرد 1: درخواست تکرار"),
            ("en", "Sorry, could you repeat that?"),
            ("fa", "این یک راه مودبانه برای درخواست تکرار است وقتی چیزی را نشنیده‌ایم."),
            ("en", "Pardon? / Sorry?"),
            ("fa", "Pardon و Sorry با آهنگ بالارونده، راه‌های کوتاه و مودبانه برای درخواست تکرار هستند."),
            ("h2", "کاربرد 2: درخواست توضیح"),
            ("en", "What do you mean?"),
            ("fa", "این عبارت وقتی به کار می‌رود که کلمه‌ها را شنیده‌ایم اما معنای آن را نفهمیده‌ایم."),
            ("en", "Could you explain that again?"),
            ("fa", "این درخواست مودبانه برای توضیح دوباره یک موضوع است."),
            ("h2", "نکته مهم"),
            ("fa", "گفتن What؟ به‌تنهایی می‌تواند بی‌ادبانه به نظر برسد. بهتر است از Sorry؟ یا Pardon؟ استفاده کنید که مودبانه‌تر هستند."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Could you speak more slowly, please?"),
            ("fa", "این درخواست مودبانه برای آهسته‌تر صحبت کردن است."),
            ("en", "Do you mean the blue one?"),
            ("fa", "این جمله برای مطمئن شدن از منظور طرف مقابل به کار می‌رود."),
        ],
    },
    {
        "file": "fn-expressing-preferences.json",
        "name": "Expressing preferences",
        "levelId": 3, "order": 10, "mins": 7,
        "description": "بیان ترجیح با prefer و would rather.",
        "blocks": [
            ("h1", "بیان ترجیح"),
            ("fa", "برای گفتن اینکه چه چیزی را بیشتر دوست داریم، از ساختارهایی مثل prefer و would rather استفاده می‌کنیم. هرکدام قاعده دستوری کمی متفاوتی دارند."),
            ("h2", "کاربرد 1: prefer"),
            ("en", "I prefer tea to coffee."),
            ("fa", "بعد از prefer برای مقایسه دو چیز از to استفاده می‌کنیم، نه than."),
            ("en", "She prefers walking to driving."),
            ("fa", "بعد از prefer می‌توان فعل ing-دار هم آورد و باز هم مقایسه با to انجام می‌شود."),
            ("h2", "کاربرد 2: would rather"),
            ("en", "I'd rather stay home."),
            ("fa", "بعد از would rather فعل ساده و بدون to می‌آید. این یک تفاوت مهم با prefer است."),
            ("en", "I'd rather walk than drive."),
            ("fa", "وقتی would rather دو گزینه را مقایسه می‌کند، از than استفاده می‌کنیم، نه to."),
            ("h2", "نکته مهم"),
            ("fa", "نکته کلیدی در حرف اضافه است: prefer A to B اما would rather A than B. همچنین بعد از would rather فعل ساده می‌آید، نه to."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "I prefer summer to winter."),
            ("fa", "prefer با to برای مقایسه دو فصل به کار رفته است."),
            ("en", "Would you rather have tea or coffee?"),
            ("fa", "این یک سوال مودبانه برای پرسیدن ترجیح طرف مقابل است."),
        ],
    },
    {
        "file": "fn-invitations.json",
        "name": "Invitations",
        "levelId": 3, "order": 11, "mins": 7,
        "description": "دعوت کردن و پذیرفتن یا رد کردن مودبانه.",
        "blocks": [
            ("h1", "دعوت کردن"),
            ("fa", "دعوت کردن و پاسخ دادن به دعوت بخش مهمی از گفتگوهای اجتماعی است. رد کردن دعوت باید مودبانه باشد و معمولا با یک دلیل کوتاه همراه است."),
            ("h2", "کاربرد 1: دعوت کردن"),
            ("en", "Would you like to join us?"),
            ("fa", "Would you like to یک دعوت مودبانه است و بعد از آن فعل ساده با to می‌آید."),
            ("en", "Do you want to come over?"),
            ("fa", "Do you want to دوستانه‌تر و غیررسمی‌تر است و میان دوستان به کار می‌رود."),
            ("h2", "کاربرد 2: پذیرفتن و رد کردن"),
            ("en", "I'd love to, thanks!"),
            ("fa", "I'd love to یک راه گرم برای پذیرفتن دعوت است."),
            ("en", "I'd love to, but I'm busy."),
            ("fa", "برای رد کردن مودبانه، اول تشکر می‌کنیم و سپس با but یک دلیل کوتاه می‌آوریم."),
            ("h2", "نکته مهم"),
            ("fa", "رد کردن مستقیم مثل No بدون توضیح بی‌ادبانه است. بهتر است ابتدا تمایل خود را نشان دهید و سپس با یک دلیل کوتاه عذرخواهی کنید."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "How about dinner on Friday?"),
            ("fa", "How about یک راه دوستانه برای دعوت کردن است."),
            ("en", "Sorry, I can't make it."),
            ("fa", "make it یعنی توانستن حاضر شدن؛ این یک راه مودبانه برای رد کردن است."),
        ],
    },
    {
        "file": "fn-telephone-language.json",
        "name": "Telephone language",
        "levelId": 3, "order": 12, "mins": 8,
        "description": "عبارت‌های رایج برای گفتگوی تلفنی.",
        "blocks": [
            ("h1", "زبان تلفن"),
            ("fa", "گفتگوی تلفنی عبارت‌های ثابت خود را دارد که با گفتگوی رو در رو فرق می‌کند. دانستن این عبارت‌ها به مکالمه روان‌تر پشت تلفن کمک می‌کند."),
            ("h2", "کاربرد 1: شروع تماس"),
            ("en", "Hello, this is Sara speaking."),
            ("fa", "پشت تلفن برای معرفی خود از this is استفاده می‌کنیم، نه I am. این یک قاعده ثابت است."),
            ("en", "Can I speak to Mr Brown, please?"),
            ("fa", "این عبارت مودبانه برای خواستن صحبت با یک شخص مشخص است."),
            ("h2", "کاربرد 2: پیام و انتظار"),
            ("en", "Can I take a message?"),
            ("fa", "وقتی شخص موردنظر در دسترس نیست، با این عبارت پیشنهاد گرفتن پیام می‌دهیم."),
            ("en", "Hold on a moment, please."),
            ("fa", "Hold on یعنی یک لحظه پشت خط بمانید. این عبارت رایج هنگام انتقال تماس است."),
            ("h2", "نکته مهم"),
            ("fa", "پشت تلفن برای معرفی خود از this is استفاده می‌کنیم و برای پرسیدن طرف مقابل از Who's calling؟. گفتن I am Sara پشت تلفن طبیعی نیست."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "Sorry, you've got the wrong number."),
            ("fa", "این عبارت وقتی به کار می‌رود که تماس‌گیرنده شماره را اشتباه گرفته است."),
            ("en", "Could you call back later?"),
            ("fa", "call back یعنی دوباره تماس گرفتن؛ این درخواست مودبانه برای تماس مجدد است."),
        ],
    },

    # ===================== More real-world practical ==========================
    {
        "file": "rw-personal-information.json",
        "name": "Personal information",
        "levelId": 1, "order": 16, "mins": 7,
        "description": "دادن و پرسیدن اطلاعات شخصی در فرم‌ها و معرفی.",
        "blocks": [
            ("h1", "اطلاعات شخصی"),
            ("fa", "دادن و پرسیدن اطلاعات شخصی مثل نام، نشانی و شغل در معرفی خود و پر کردن فرم‌ها بسیار کاربردی است. هر اطلاعات سوال مخصوص خود را دارد."),
            ("h2", "کاربرد 1: نام و ملیت"),
            ("en", "What's your full name?"),
            ("fa", "full name یعنی نام و نام خانوادگی کامل. این سوال رایج در فرم‌ها و موقعیت‌های رسمی است."),
            ("en", "Where are you from?"),
            ("fa", "این سوال درباره ملیت یا اهل کجا بودن است و جواب آن با I'm from می‌آید."),
            ("h2", "کاربرد 2: نشانی و شغل"),
            ("en", "What's your address?"),
            ("fa", "address یعنی نشانی محل زندگی. این اطلاعات معمولا در فرم‌ها خواسته می‌شود."),
            ("en", "What do you do?"),
            ("fa", "این سوال درباره شغل است، نه کاری که همین حالا انجام می‌دهید. جواب آن با I'm a می‌آید، مثل I'm a teacher."),
            ("h2", "نکته مهم"),
            ("fa", "برای گفتن شغل از حرف a استفاده می‌کنیم: I'm a doctor، نه I'm doctor. همچنین What do you do؟ یعنی شغلت چیست، نه چه می‌کنی."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "How old are you?"),
            ("fa", "برای سن از فعل be استفاده می‌کنیم: I'm twenty، نه I have twenty."),
            ("en", "What's your phone number?"),
            ("fa", "این سوال برای گرفتن شماره تلفن است و شماره را معمولا رقم‌به‌رقم می‌گوییم."),
        ],
    },
    {
        "file": "rw-quantities-and-measurements.json",
        "name": "Quantities and measurements",
        "levelId": 2, "order": 17, "mins": 7,
        "description": "بیان مقدار با a kilo of و a bottle of.",
        "blocks": [
            ("h1", "مقدار و اندازه"),
            ("fa", "برای خرید و آشپزی باید بتوانیم مقدار چیزها را بیان کنیم. برای اسم‌های غیرقابل‌شمارش از ظرف یا واحد اندازه به همراه of استفاده می‌کنیم."),
            ("h2", "کاربرد 1: واحدهای وزن و حجم"),
            ("en", "I need a kilo of rice."),
            ("fa", "a kilo of برای بیان وزن یک ماده غیرقابل‌شمارش مثل برنج به کار می‌رود."),
            ("en", "She bought a litre of milk."),
            ("fa", "a litre of برای بیان حجم مایعات استفاده می‌شود."),
            ("h2", "کاربرد 2: ظرف‌ها و بسته‌ها"),
            ("en", "a bottle of water"),
            ("fa", "برای مایعات اغلب از نام ظرف استفاده می‌کنیم، مثل a bottle of یا a glass of."),
            ("en", "a packet of biscuits"),
            ("fa", "a packet of برای چیزهایی است که در بسته فروخته می‌شوند."),
            ("h2", "نکته مهم"),
            ("fa", "اسم‌های غیرقابل‌شمارش مثل rice و water را مستقیم جمع نمی‌بندیم. به‌جای آن از واحد یا ظرف به همراه of استفاده می‌کنیم: two bottles of water."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "a piece of cake"),
            ("fa", "a piece of برای یک تکه از چیزی بزرگ‌تر به کار می‌رود."),
            ("en", "a cup of coffee"),
            ("fa", "a cup of یک واحد رایج برای نوشیدنی‌های گرم است."),
        ],
    },
    {
        "file": "rw-ordinal-numbers-and-dates.json",
        "name": "Ordinal numbers and dates",
        "levelId": 1, "order": 17, "mins": 7,
        "description": "اعداد ترتیبی و گفتن تاریخ‌ها.",
        "blocks": [
            ("h1", "اعداد ترتیبی و تاریخ"),
            ("fa", "اعداد ترتیبی مثل first و second ترتیب چیزها را نشان می‌دهند و برای گفتن تاریخ‌ها لازم هستند. گفتن تاریخ کمی با نوشتن آن فرق دارد."),
            ("h2", "کاربرد 1: اعداد ترتیبی"),
            ("en", "first, second, third"),
            ("fa", "سه عدد ترتیبی اول بی‌قاعده‌اند. از چهارم به بعد معمولا با افزودن th ساخته می‌شوند، مثل fourth و fifth."),
            ("en", "This is my second visit."),
            ("fa", "second ترتیب را نشان می‌دهد، یعنی بازدید دوم. اعداد ترتیبی پیش از اسم می‌آیند."),
            ("h2", "کاربرد 2: گفتن تاریخ"),
            ("en", "It's the third of June."),
            ("fa", "در گفتار تاریخ، از عدد ترتیبی و حرف of استفاده می‌کنیم، هرچند در نوشتار به‌صورت 3 June می‌آید."),
            ("en", "My birthday is on the tenth of May."),
            ("fa", "برای تاریخ روز از on و عدد ترتیبی استفاده می‌کنیم."),
            ("h2", "نکته مهم"),
            ("fa", "تاریخ اغلب با عدد ترتیبی خوانده می‌شود، حتی وقتی th نوشته نشده باشد؛ پس 5 May را the fifth of May می‌خوانیم."),
            ("h2", "مثال‌های بیشتر"),
            ("en", "She came first in the race."),
            ("fa", "first اینجا ترتیب رتبه را نشان می‌دهد."),
            ("en", "The meeting is on the twenty-first."),
            ("fa", "twenty-first عدد ترتیبی بیست‌ویکم است و برای تاریخ به کار رفته است."),
        ],
    },
]


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    count = 0
    for topic in TOPICS:
        data = build(topic)
        path = os.path.join(OUT_DIR, topic["file"])
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        count += 1
    print(f"Wrote {count} files to {os.path.abspath(OUT_DIR)}")


if __name__ == "__main__":
    main()
